AWSTemplateFormatVersion: 2010-09-09
Description: Bastion host setup

Parameters:

  NetworkStackName:
    Type: String
    Description: The name of the network stack
  InstanceType:
    Type: String
    Description: The instance type to use for the EC2 instance
    Default: t3.nano
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The name of the SSH key pair

Resources:

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchTemplate:
        LaunchTemplateId:
          Ref: LaunchTemplate
        Version:
          Fn::GetAtt: LaunchTemplate.LatestVersionNumber
      VPCZoneIdentifier:
        - Fn::ImportValue:
            Fn::Sub: ${NetworkStackName}-PublicSubnet1
        - Fn::ImportValue:
            Fn::Sub: ${NetworkStackName}-PublicSubnet2
        - Fn::ImportValue:
            Fn::Sub: ${NetworkStackName}-PublicSubnet3
      MinSize: 0
      MaxSize: 1
      DesiredCapacity: 1

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        InstanceType:
          Ref: InstanceType
        ImageId: ami-0713f98de93617bb4
        SecurityGroupIds:
          - Fn::ImportValue:
              Fn::Sub: ${NetworkStackName}-BastionHostSecurityGroup
        KeyName:
          Ref: KeyName
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: Bastion Host
          - ResourceType: volume
            Tags:
              - Key: Name
                Value: Bastion Host
        InstanceMarketOptions:
          MarketType: spot
          SpotOptions:
            SpotInstanceType: one-time
            InstanceInterruptionBehavior: terminate
        UserData:
          Fn::Base64:
            Fn::Join:
              - ''
              - - "#!/bin/bash\n"
                - "yum -y --security update\n"
